### ISSUE TITLE
The type initializer for 'Un4seen.Bass.Bass' threw an exception.

### ISSUE THREAD

**Issue by heldersepu** [ProfessorCattington/MP3-splitter#1]
1. Forked the project 
2. Open project in Visual Studio 2015
3. Rebuild project
4. Try to run, I get error below:

Unable to load DLL 'bass.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   at Un4seen.Bass.Bass.BASS_Init(Int32 device, Int32 freq, BASSInit flags, IntPtr win)
   at ColdCutsNS.Program.Main() in ...\GitHub\MP3-splitter\coldcuts\Program.cs:line 19
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ProfessorCattington** [comment]
Uh oh! I'll get on this when I get home tonight

**Comment by heldersepu** [comment]
I forked your repo and also looking for a solution...
On a fresh start Bass.net should be downloaded from NuGet

**Comment by heldersepu** [comment]
I think that I got the project to a good place...
- No more ```\bin``` and ```\obj``` folders on git, those are generated every time we build
- Remove the hardcoded BASS.NET, now the project uses the NuGet version

See my fork for more details:
https://github.com/heldersepu/MP3-splitter/commits/master
The only thing, I'm not sure about one file: **lame.exe** Is that needed?
